# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbbab9e4e5a843bca2936a3c943e157afa88e0ae65fa313d908249791e28eae0630b2349c5c109b07ff66e06884431ffe3b162ffb968622fabba17dca29327b4

test:
  secret_key_base: 072a721844e0a01512e10dc4cf55002417733257fc9fbd1631a13d8d463f3fe237bca806444f1632b73d48fe2449895820ad989af05b62893a9054c19e0f9bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
